/**
 * Created by ZHANGXI on 2018/1/17.
 */
// priv module
export const PRODUCT_QUERY_PRODUCT_BEGIN = 'PRODUCT_QUERY_PRODUCT_BEGIN'
export const PRODUCT_QUERY_PRODUCT_SUC = 'PRODUCT_QUERY_PRODUCT_SUC'
export const PRODUCT_QUERY_ROOT_PRODUCTS_BEGIN = 'PRODUCT_QUERY_ROOT_PRODUCTS_BEGIN'
export const PRODUCT_QUERY_ROOT_PRODUCTS_SUC = 'PRODUCT_QUERY_ROOT_PRODUCTS_SUC'
export const PRODUCT_QUERY_PRODUCTS_BEGIN = 'PRODUCT_QUERY_PRODUCTS_BEGIN'
export const PRODUCT_QUERY_PRODUCTS_SUC = 'PRODUCT_QUERY_PRODUCTS_SUC'
export const PRODUCT_QUERY_PRODUCTS_COUNT_BEGIN = 'PRODUCT_QUERY_PRODUCTS_COUNT_BEGIN'
export const PRODUCT_QUERY_PRODUCTS_COUNT_SUC = 'PRODUCT_QUERY_PRODUCTS_COUNT_SUC'
export const PRODUCT_ADD_SUC = 'PRODUCT_ADD_SUC'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'
export const PRODUCT_UPDATE_SUC = 'PRODUCT_UPDATE_SUC'
export const PRODUCT_DELETE_BEGIN = 'PRODUCT_DELETE_BEGIN'
export const PRODUCT_DELETE_SUC = 'PRODUCT_DELETE_SUC'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
export const PRODUCT_UPLOAD_SUC = 'PRODUCT_UPLOAD_SUC'

