/**
 * Created by ZHANGXI on 2018/1/17.
 */
// priv module
export const PRODUCTTYPE_QUERY_PRODUCTTYPE_BEGIN = 'PRODUCTTYPE_QUERY_PRODUCTTYPE_BEGIN'
export const PRODUCTTYPE_QUERY_PRODUCTTYPE_SUC = 'PRODUCTTYPE_QUERY_PRODUCTTYPE_SUC'
export const PRODUCTTYPE_QUERY_ROOT_PRODUCTTYPES_BEGIN = 'PRODUCTTYPE_QUERY_ROOT_PRODUCTTYPES_BEGIN'
export const PRODUCTTYPE_QUERY_ROOT_PRODUCTTYPES_SUC = 'PRODUCTTYPE_QUERY_ROOT_PRODUCTTYPES_SUC'
export const PRODUCTTYPE_QUERY_PRODUCTTYPES_BEGIN = 'PRODUCTTYPE_QUERY_PRODUCTTYPES_BEGIN'
export const PRODUCTTYPE_QUERY_PRODUCTTYPES_SUC = 'PRODUCTTYPE_QUERY_PRODUCTTYPES_SUC'
export const PRODUCTTYPE_QUERY_PRODUCTTYPES_COUNT_BEGIN = 'PRODUCTTYPE_QUERY_PRODUCTTYPES_COUNT_BEGIN'
export const PRODUCTTYPE_QUERY_PRODUCTTYPES_COUNT_SUC = 'PRODUCTTYPE_QUERY_PRODUCTTYPES_COUNT_SUC'
export const PRODUCTTYPE_ADD_SUC = 'PRODUCTTYPE_ADD_SUC'
export const PRODUCTTYPE_ADD_FAIL = 'PRODUCTTYPE_ADD_FAIL'
export const PRODUCTTYPE_UPDATE_SUC = 'PRODUCTTYPE_UPDATE_SUC'
export const PRODUCTTYPE_DELETE_BEGIN = 'PRODUCTTYPE_DELETE_BEGIN'
export const PRODUCTTYPE_DELETE_SUC = 'PRODUCTTYPE_DELETE_SUC'
export const PRODUCTTYPE_DELETE_FAIL = 'PRODUCTTYPE_DELETE_FAIL'
export const PRODUCTTYPE_UPLOAD_SUC = 'PRODUCTTYPE_UPLOAD_SUC'

