/**
 * Created by ZHANGXI on 2018/3/13.
 */
export const WITHDRAW_QUERY_BEGIN = 'WITHDRAW_QUERY_BEGIN'
export const WITHDRAW_QUERY_SUC = 'WITHDRAW_QUERY_SUC'
export const WITHDRAW_SUC = 'WITHDRAW_SUC'
export const CHECKFAIL_SUC = 'CHECKFAIL_SUC'
