/**
 * Created by ZHANGXI on 2018/1/16.
 */
// priv module
export const BRAND_QUERY_BRAND_BEGIN = 'BRAND_QUERY_BRAND_BEGIN'
export const BRAND_QUERY_BRAND_SUC = 'BRAND_QUERY_BRAND_SUC'
export const BRAND_QUERY_ROOT_BRANDS_BEGIN = 'BRAND_QUERY_ROOT_BRANDS_BEGIN'
export const BRAND_QUERY_ROOT_BRANDS_SUC = 'BRAND_QUERY_ROOT_BRANDS_SUC'
export const BRAND_QUERY_BRANDS_BEGIN = 'BRAND_QUERY_BRANDS_BEGIN'
export const BRAND_QUERY_BRANDS_SUC = 'BRAND_QUERY_BRANDS_SUC'
export const BRAND_QUERY_BRANDS_COUNT_BEGIN = 'BRAND_QUERY_BRANDS_COUNT_BEGIN'
export const BRAND_QUERY_BRANDS_COUNT_SUC = 'BRAND_QUERY_BRANDS_COUNT_SUC'
export const BRAND_ADD_SUC = 'BRAND_ADD_SUC'
export const BRAND_ADD_FAIL = 'BRAND_ADD_FAIL'
export const BRAND_UPDATE_SUC = 'BRAND_UPDATE_SUC'
export const BRAND_DELETE_BEGIN = 'BRAND_DELETE_BEGIN'
export const BRAND_DELETE_SUC = 'BRAND_DELETE_SUC'
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL'
export const BRAND_UPLOAD_SUC = 'BRAND_UPLOAD_SUC'
