/**
 * Created by ZHANGXI on 2018/2/26.
 */
export const ORDER_DISPATCH_QUERY_COUNT_BEGIN = 'ORDER_DISPATCH_QUERY_COUNT_BEGIN'
export const ORDER_DISPATCH_QUERY_COUNT_SUC = 'ORDER_DISPATCH_QUERY_COUNT_SUC'
export const ORDER_DISPATCH_QUERY_BEGIN = 'ORDER_DISPATCH_QUERY_BEGIN'
export const ORDER_DISPATCH_QUERY_SUC = 'ORDER_DISPATCH_QUERY_SUC'
export const ORDER_DISPATCH_SUC = 'ORDER_DISPATCH_SUC'
