/**
 * Created by ZHANGXI on 2018/3/27.
 */
export const BALANCE_QUERY_BEGIN = 'BALANCE_QUERY_BEGIN'
export const BALANCE_QUERY_SUC = 'BALANCE_QUERY_SUC'
export const BALANCE_SUC = 'BALANCE_SUC'
export const BALANCE_SUMMARY_QUERY_BEGIN = 'BALANCE_SUMMARY_QUERY_BEGIN'
export const BALANCE_SUMMARY_QUERY_SUC = 'BALANCE_SUMMARY_QUERY_SUC'


