/**
 * Created by ZHANGXI on 2018/2/12.
 */
export const PURCHASE_QUERY_PURCHASE_BEGIN = 'PURCHASE_QUERY_PURCHASE_BEGIN'
export const PURCHASE_QUERY_PURCHASE_SUC = 'PURCHASE_QUERY_PURCHASE_SUC'
export const PURCHASE_QUERY_ROOT_PURCHASES_BEGIN = 'PURCHASE_QUERY_ROOT_PURCHASES_BEGIN'
export const PURCHASE_QUERY_ROOT_PURCHASES_SUC = 'PURCHASE_QUERY_ROOT_PURCHASES_SUC'
export const PURCHASE_QUERY_PURCHASES_BEGIN = 'PURCHASE_QUERY_PURCHASES_BEGIN'
export const PURCHASE_QUERY_PURCHASES_SUC = 'PURCHASE_QUERY_PURCHASES_SUC'
export const PURCHASE_QUERY_PURCHASES_COUNT_BEGIN = 'PURCHASE_QUERY_PURCHASES_COUNT_BEGIN'
export const PURCHASE_QUERY_PURCHASES_COUNT_SUC = 'PURCHASE_QUERY_PURCHASES_COUNT_SUC'
export const PURCHASE_ADD_SUC = 'PURCHASE_ADD_SUC'
export const PURCHASE_ADD_FAIL = 'PURCHASE_ADD_FAIL'
export const PURCHASE_UPDATE_SUC = 'PURCHASE_UPDATE_SUC'
export const PURCHASE_DELETE_BEGIN = 'PURCHASE_DELETE_BEGIN'
export const PURCHASE_DELETE_SUC = 'PURCHASE_DELETE_SUC'
export const PURCHASE_DELETE_FAIL = 'PURCHASE_DELETE_FAIL'
export const PURCHASE_UPLOAD_SUC = 'PURCHASE_UPLOAD_SUC'
