/**
 * Created by ZHANGXI on 2018/1/17.
 */
// priv module
export const SUPPORT_QUERY_SUPPORT_BEGIN = 'SUPPORT_QUERY_SUPPORT_BEGIN'
export const SUPPORT_QUERY_SUPPORT_SUC = 'SUPPORT_QUERY_SUPPORT_SUC'
export const SUPPORT_QUERY_ROOT_SUPPORTS_BEGIN = 'SUPPORT_QUERY_ROOT_SUPPORTS_BEGIN'
export const SUPPORT_QUERY_ROOT_SUPPORTS_SUC = 'SUPPORT_QUERY_ROOT_SUPPORTS_SUC'
export const SUPPORT_QUERY_SUPPORTS_BEGIN = 'SUPPORT_QUERY_SUPPORTS_BEGIN'
export const SUPPORT_QUERY_SUPPORTS_SUC = 'SUPPORT_QUERY_SUPPORTS_SUC'
export const SUPPORT_QUERY_SUPPORTS_COUNT_BEGIN = 'SUPPORT_QUERY_SUPPORTS_COUNT_BEGIN'
export const SUPPORT_QUERY_SUPPORTS_COUNT_SUC = 'SUPPORT_QUERY_SUPPORTS_COUNT_SUC'
export const SUPPORT_ADD_SUC = 'SUPPORT_ADD_SUC'
export const SUPPORT_ADD_FAIL = 'SUPPORT_ADD_FAIL'
export const SUPPORT_UPDATE_SUC = 'SUPPORT_UPDATE_SUC'
export const SUPPORT_DELETE_BEGIN = 'SUPPORT_DELETE_BEGIN'
export const SUPPORT_DELETE_SUC = 'SUPPORT_DELETE_SUC'
export const SUPPORT_DELETE_FAIL = 'SUPPORT_DELETE_FAIL'
export const SUPPORT_UPLOAD_SUC = 'SUPPORT_UPLOAD_SUC'
